development:
  cloud_name: spacelender-cloud
  api_key: '975475732752396'
  api_secret: EEpmyuHG12jqZDkKrNDgnrPTqfY
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: spacelender-cloud
  api_key: '975475732752396'
  api_secret: EEpmyuHG12jqZDkKrNDgnrPTqfY
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: spacelender-cloud
  api_key: '975475732752396'
  api_secret: EEpmyuHG12jqZDkKrNDgnrPTqfY
  enhance_image_tag: true
  static_image_support: false
